apiVersion: v1
appVersion: "1.0"
description: Elixir producer-consumer. Retrieves streamed data, and loads it onto a Kafka topic
name: reaper
version: 1.2.9
sources:
  - https://github.com/UrbanOS-Public/smartcitiesdata/tree/master/apps/reaper
