defmodule AndiWeb.Views.DisplayNames do
  @moduledoc false

  @display_names %{
    action: "Method",
    benefitRating: "Benefit",
    body: "Body",
    cacheTtl: "Cache Duration",
    cadence: "Cadence",
    conditionCompareTo: "Compare To",
    conditionDataType: "Comparison Value Type",
    conditionOperation: "Comparison",
    conditionSourceDateFormat: "Source Date Format",
    conditionTargetDateFormat: "Target Date Format",
    contactEmail: "Maintainer Email",
    datasetOwner: "Dataset Owner",
    contactName: "Maintainer Name",
    dataJsonUrl: "Data JSON URL",
    dataName: "Data Name",
    dataTitle: "Dataset Title",
    date: "Date",
    day: "Day",
    deltaTimeUnit: "Time Offset Units",
    deltaTimeValue: "Time Offset Value",
    description: "Description",
    destination: "Destination",
    format: "Format",
    headers: "Headers",
    homepage: "Homepage URL",
    hour: "Hour",
    id: "ID",
    ingestion_field_selector: "Ingestion Field",
    issuedDate: "Release Date",
    itemType: "Item Type",
    keywords: "Keywords",
    language: "Language",
    license: "License",
    logoUrl: "Logo URL",
    method: "Method",
    minute: "Minute",
    modifiedDate: "Last Updated",
    month: "Month",
    name: "Name",
    orgId: "Organization",
    orgName: "Organization Name",
    orgTitle: "Organization Title",
    path: "Response Location",
    private: "Level of Access",
    publishFrequency: "Update Frequency",
    queryParams: "Query Parameters",
    riskRating: "Risk",
    schema: "Schema",
    second: "Second",
    secret_value: "Value",
    selector: "Selector",
    sourceConditionField: "Comparison Field",
    sourceFormat: "Source Format",
    sourceHeaders: "Headers",
    sourceQueryParams: "Query Parameters",
    sourceType: "Source Type",
    sourceUrl: "Base URL",
    spatial: "Spatial Boundaries",
    sub_key: "Name",
    targetConditionField: "Target Field",
    targetConditionValue: "Target Value",
    targetDatasets: "Target Datasets",
    temporal: "Temporal Boundaries",
    time: "Time",
    topLevelSelector: "Top Level Selector",
    transformationType: "Transformation Type",
    type: "Type",
    url: "URL",
    week: "Week",
    year: "Year",
    datasetLink: "Dataset Link"
  }

  def get(field_key) do
    Map.get(@display_names, field_key)
  end
end
