apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kdp.metastore.fullname" . }}
  labels:
    component: metastore
{{ include "kdp.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      component: metastore
{{ include "kdp.labels" . | indent 6 }}
  replicas: {{ .Values.metastore.deploy.replicas }}
  strategy:
{{ toYaml .Values.metastore.deploy.updateStrategy | trim | indent 4 }}
  template:
    metadata:
      annotations:
        checksum/core-site-configmap: {{ include (print $.Template.BasePath "/shared-configs/core-site.yaml") . | sha256sum }}
        checksum/metastore-site-configmap: {{ include (print $.Template.BasePath "/metastore/metastore-site.yaml") . | sha256sum }}
        prometheus.io/port: "8181"
        prometheus.io/scrape: "true"
      labels:
        component: metastore
{{ include "kdp.labels" . | indent 8 }}
    spec:
      initContainers:
      - name: init-schema
        image: {{ .Values.metastore.deploy.container.image }}:{{ .Values.metastore.deploy.container.tag }}
        imagePullPolicy: {{ .Values.metastore.deploy.container.pullPolicy }}
        resources:
{{ toYaml .Values.metastore.deploy.container.resources | indent 10 }}
        command:
        - /bin/bash
        - -c
        args:
        - /opt/hive-metastore/bin/schematool -dbType postgres -validate || /opt/hive-metastore/bin/schematool -dbType postgres -initSchema
        volumeMounts:
        - mountPath: /opt/hive-metastore/conf/metastore-site.xml
          name: metastore-site
          subPath: metastore-site.xml
      containers:
      - name: metastore
        image: {{ .Values.metastore.deploy.container.image }}:{{ .Values.metastore.deploy.container.tag }}
        imagePullPolicy: {{ .Values.metastore.deploy.container.pullPolicy }}
        command:
        - /opt/hive-metastore/bin/start-metastore
        ports:
        - containerPort: {{ .Values.metastore.service.port }}
          name: metastore
        volumeMounts:
        - mountPath: /opt/hive-metastore/conf/metastore-site.xml
          name: metastore-site
          subPath: metastore-site.xml
        - mountPath: /opt/hadoop/etc/hadoop/core-site.xml
          name: core-site
          subPath: core-site.xml
        - mountPath: /opt/hive-metastore/jmx_exporter_config.yaml
          name: metastore-configs
          subPath: jmx_exporter_config.yaml
        env:
        - name: HADOOP_OPTS
          value: >
            -server
            -Xmx{{ .Values.metastore.jvm.maxHeapSize }}
            -XX:+{{ .Values.metastore.jvm.gcMethod.type }}
            -XX:G1HeapRegionSize={{ .Values.metastore.jvm.gcMethod.g1.heapRegionSize }}
            -XX:+UseGCOverheadLimit
            -XX:+ExplicitGCInvokesConcurrent
            -XX:+HeapDumpOnOutOfMemoryError
            -XX:+ExitOnOutOfMemoryError
            -javaagent:/opt/hive-metastore/jmx_exporter.jar=8181:/opt/hive-metastore/jmx_exporter_config.yaml
        resources:
{{ toYaml .Values.metastore.deploy.container.resources | indent 10 }}
      volumes:
      - name: metastore-site
        configMap:
          name: {{ template "kdp.metastore.fullname" . }}-config
      - name: core-site
        configMap:
          name: {{ template "kdp.name" . }}-core-site
      - name: metastore-configs
        configMap:
          name: {{ template "kdp.metastore.fullname" . }}-metastore-configs
