apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdp.metastore.fullname" . }}
  labels:
    component: metastore
{{ include "kdp.labels" . | indent 4 }}
spec:
  type: {{ .Values.metastore.service.type }}
  ports:
  - port: {{ .Values.metastore.service.port }}
    targetPort: metastore
    name: metastore
  selector:
    component: metastore
{{ include "kdp.labels" . | indent 4 }}
