apiVersion: v1
kind: Service
metadata:
  name: hive-metastore
  labels:
    component: metastore
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: hive-metastore
  selector:
    app: hive-metastore