{{- if .Values.metastore.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hive-metastore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hive-metastore
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: anyuid
subjects:
- kind: ServiceAccount
  name: hive-metastore
  namespace: {{ .Release.Namespace }}
{{- end }}