{{- if index .Values "minio-tenant" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "minio-tenant" "tenant" "users" 0 "name" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CONSOLE_ACCESS_KEY: {{ .Values.secrets.minio.base64UserAccessKey }}
  CONSOLE_SECRET_KEY: {{ .Values.secrets.minio.base64UserSecretKey }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ index .Values "minio-tenant" "tenant" "configuration" "name" }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.secrets.minio.rootUserName | quote }}
    export MINIO_ROOT_PASSWORD={{ .Values.secrets.minio.rootPassword | quote }}
{{- end }}
