apiVersion: v1
kind: ServiceAccount
metadata:
  name: updater-cron
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-sauron-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sauron-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sauron-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sauron-role
subjects:
- kind: ServiceAccount
  name: updater-cron
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-sauron-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-sauron-role
subjects:
- kind: ServiceAccount
  name: updater-cron
  namespace: {{ .Release.Namespace }}
