apiVersion: v1
appVersion: "1.0"
description: Dynamically find kafka topics and makes available corresponding channels on a public websocket
name: discovery-streams
version: 1.1.9
sources:
  - https://github.com/UrbanOS-Public/smartcitiesdata/tree/master/apps/discovery_streams
