apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "helm.name" . }}
  ports:
  - name: http
    port: 80
    targetPort: 4000
    protocol: TCP
  type: NodePort
