{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-patcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-patcher
rules:
  - apiGroups: [""]
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-patcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kafka-patcher
subjects:
- kind: ServiceAccount
  name: kafka-patcher
  namespace: {{ .Release.Namespace }}
{{- end }}