---
version: '3.4'
services:
  init:
    image: alpine:3.16.0
    platform: linux/amd64
    volumes:
      - ${PWD}/test/integration:/workdir
      - minio:/minio
    entrypoint: /workdir/setup.sh
  minio:
    image: minio/minio:RELEASE.2022-10-15T19-57-03Z.fips
    platform: linux/amd64
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    ports:
    - "9000:9000"
    - "9001:9001"
    depends_on:
      - init
  zookeeper:
    image: wurstmeister/zookeeper
    platform: linux/amd64
    ports:
    - "2181:2181"
  kafka:
    image: bitnami/kafka:3.1.2
    platform: linux/amd64
    depends_on:
    - zookeeper
    ports:
    - "9092:9092"
    expose:
    - "9094"
    environment:
    - "KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://:9094,OUTSIDE://${HOST_IP:-localhost}:9092"
    - "KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - "KAFKA_CFG_LISTENERS=INSIDE://:9094,OUTSIDE://:9092"
    - "KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INSIDE"
    - "KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181"
    - "ALLOW_PLAINTEXT_LISTENER=yes"
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 10s
      timeout: 20s
      retries: 3

  kafka-init:
    image: bitnami/kafka:3.1.2
    platform: linux/amd64
    depends_on:
      - kafka
    entrypoint: ['/bin/bash', '-c']
    command: |
      "
      echo -e 'Creating kafka topics'
      kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic event-stream --replication-factor 1 --partitions 1
      kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic streaming-transformed --replication-factor 1 --partitions 1
      kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic dead-letters --replication-factor 1 --partitions 1
      kafka-topics.sh --bootstrap-server kafka:9094 --create --if-not-exists --topic streaming-persisted --replication-factor 1 --partitions 1
      echo -e 'Successfully created the following topics:'
      kafka-topics.sh --bootstrap-server kafka:9094 --list
      "

  redis:
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
  sftp:
    image: atmoz/sftp:alpine
    platform: linux/amd64
    ports: 
     - "2222:22"
    command: "sftp_user:sftp_password:1001::upload"

volumes:
  minio:
