apiVersion: v1
kind: Secret
metadata:
  name: discovery-api-presign-key
type: Opaque
stringData:
  discovery-api-presign-key: {{ quote .Values.secrets.discoveryApiPresignKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: guardian-secret-key
type: Opaque
stringData:
  guardian-secret-key: {{ quote .Values.secrets.guardianSecretKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-discovery-api-aws-credentials
type: Opaque
stringData:
  {{ if .Values.global.objectStore.accessSecret }}
  aws_access_key_secret: {{ quote .Values.global.objectStore.accessSecret }}
  {{- else }}
  aws_access_key_secret: {{ quote .Values.aws.accessKeySecret }}
  {{ end -}}  
  {{ if .Values.global.objectStore.accessKey }}
  aws_access_key_id: {{ quote .Values.global.objectStore.accessKey }}
  {{- else }}
  aws_access_key_id: {{ quote .Values.aws.accessKeyId }}
  {{ end -}}
