global:
  buckets:
    hiveStorageBucket: presto-hive-storage
  objectStore:
    host: minio
    port: 80
    accessKey: example-key
    accessSecret: example-secret
    # metastore will create this folder in the hiveStorageBucket.
    #   do not create it yourself or that will cause ownership conflict.
    hiveStoragePath: hive-s3

metastore:
  image:
    repository: quay.io/cloudservices/ubi-hive
    tag: 3.1.2-metastore-009
  rbac:
    enabled: true
  postgres:
    user: padmin
    password: example
    passwordSecret: null
    passwordSecretKey: null
    host: postgres
    port: 5432
    name: metastore
  resources:
    limits:
      memory: 2Gi
      cpu: 1
    requests:
      memory: 2Gi
      cpu: 1

trino:
  serviceAccount:
    create: true
    name: trino

  coordinator:
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 2Gi
        cpu: 1

  worker:
    resources:
      limits:
        memory: 2Gi
        cpu: 1
      requests:
        memory: 2Gi
        cpu: 1

  additionalCatalogs:
    hive: |
      connector.name=hive-hadoop2
      hive.metastore.uri=thrift://hive-metastore:8000
      hive.metastore.username=padmin
      hive.metastore-timeout=360m
      hive.allow-drop-table=true
      hive.allow-rename-table=true
      hive.allow-drop-column=true
      hive.allow-rename-column=true
      hive.allow-add-column=true
      hive.s3.aws-access-key=EXAMPLE
      hive.s3.aws-secret-key=EXAMPLE
      hive.s3.path-style-access=true
      hive.s3.endpoint=http://minio:80
      hive.s3.ssl.enabled=false
