%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%


-include("t_c_l_i_service_types.hrl").

-define(T_C_L_I_SERVICE_PRIMITIVE_TYPES, sets:from_list([0,1,2,3,4,5,6,7,8,9,15,16,17,18,19,20,21])).

-define(T_C_L_I_SERVICE_COMPLEX_TYPES, sets:from_list([10,11,12,13,14])).

-define(T_C_L_I_SERVICE_COLLECTION_TYPES, sets:from_list([10,11])).

-define(T_C_L_I_SERVICE_TYPE_NAMES, dict:from_list([{0,"BOOLEAN"},{1,"TINYINT"},{2,"SMALLINT"},{3,"INT"},{4,"BIGINT"},{5,"FLOAT"},{6,"DOUBLE"},{7,"STRING"},{8,"TIMESTAMP"},{9,"BINARY"},{10,"ARRAY"},{11,"MAP"},{12,"STRUCT"},{13,"UNIONTYPE"},{15,"DECIMAL"},{16,"NULL"},{17,"DATE"},{18,"VARCHAR"},{19,"CHAR"},{20,"INTERVAL_YEAR_MONTH"},{21,"INTERVAL_DAY_TIME"}])).

-define(T_C_L_I_SERVICE_CHARACTER_MAXIMUM_LENGTH, "characterMaximumLength").

-define(T_C_L_I_SERVICE_PRECISION, "precision").

-define(T_C_L_I_SERVICE_SCALE, "scale").

