%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(t_c_l_i_service_constants).

-include("t_c_l_i_service_types.hrl").

-export([type_names/1, type_names/2]).

type_names(0) -> "BOOLEAN";
type_names(1) -> "TINYINT";
type_names(2) -> "SMALLINT";
type_names(3) -> "INT";
type_names(4) -> "BIGINT";
type_names(5) -> "FLOAT";
type_names(6) -> "DOUBLE";
type_names(7) -> "STRING";
type_names(8) -> "TIMESTAMP";
type_names(9) -> "BINARY";
type_names(10) -> "ARRAY";
type_names(11) -> "MAP";
type_names(12) -> "STRUCT";
type_names(13) -> "UNIONTYPE";
type_names(15) -> "DECIMAL";
type_names(16) -> "NULL";
type_names(17) -> "DATE";
type_names(18) -> "VARCHAR";
type_names(19) -> "CHAR";
type_names(20) -> "INTERVAL_YEAR_MONTH";
type_names(21) -> "INTERVAL_DAY_TIME".

type_names(0, _) -> "BOOLEAN";
type_names(1, _) -> "TINYINT";
type_names(2, _) -> "SMALLINT";
type_names(3, _) -> "INT";
type_names(4, _) -> "BIGINT";
type_names(5, _) -> "FLOAT";
type_names(6, _) -> "DOUBLE";
type_names(7, _) -> "STRING";
type_names(8, _) -> "TIMESTAMP";
type_names(9, _) -> "BINARY";
type_names(10, _) -> "ARRAY";
type_names(11, _) -> "MAP";
type_names(12, _) -> "STRUCT";
type_names(13, _) -> "UNIONTYPE";
type_names(15, _) -> "DECIMAL";
type_names(16, _) -> "NULL";
type_names(17, _) -> "DATE";
type_names(18, _) -> "VARCHAR";
type_names(19, _) -> "CHAR";
type_names(20, _) -> "INTERVAL_YEAR_MONTH";
type_names(21, _) -> "INTERVAL_DAY_TIME";
type_names(_, Default) -> Default.

