apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-reaper-aws-credentials
type: Opaque
stringData:
  aws_access_key_secret: {{ quote .Values.aws.accessKeySecret }}
  aws_access_key_id: {{ quote .Values.aws.accessKeyId }}