{{- if .Values.minio.enable -}}
{{- if .Values.minio.ingress.enable -}}
{{- $serviceName := include "kdp.minio.fullname" . }}
{{- $servicePort := .Values.minio.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
{{- if .Values.minio.ingress.annotations }}
{{ toYaml .Values.minio.ingress.annotations | trim | indent 4 }}
{{- end }}
{{- if .Values.global.ingress.annotations }}
{{ toYaml .Values.global.ingress.annotations | trim | indent 4 }}
{{- end }}
  name: {{ template "kdp.minio.fullname" . }}
  labels:
    component: minio
{{ include "kdp.labels" . | indent 4 }}
spec:
  backend:
    serviceName: {{ $serviceName }}
    servicePort: {{ $servicePort }}
  rules:
{{- range .Values.minio.ingress.hosts }}
{{- $url := splitList "/" . }}
  - host: {{ first $url }}
    http:
      paths:
      - path: /{{ rest $url | join "/" }}
        backend:
          serviceName: {{ default $serviceName $.Values.minio.ingress.serviceName }}
          servicePort: {{ default $servicePort $.Values.minio.ingress.servicePort }}
{{- end }}
{{- end }}
{{- end }}
