{{- if .Values.auth.auth0_client_secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-raptor-auth0-client-secret
type: Opaque
stringData:
  auth0_client_secret: {{ quote .Values.auth.auth0_client_secret }}
{{- end }}