node ('master') {
    stage('Checkout') {
        checkout scm
        GIT_COMMIT_HASH = sh(
            script: 'git rev-parse HEAD',
            returnStdout: true
        ).trim()
    }
    stage('Build') {
        docker.build("scos/cota_streaming_consumer:${GIT_COMMIT_HASH}")
    }
    stage('Test') {
        docker.image("scos/cota_streaming_consumer:${GIT_COMMIT_HASH}")
            .inside('-e MIX_ENV=test') {
                sh('mix deps.get')
                sh('mix test')
            }
    }
}