Mox.defmock(MockReader, for: Pipeline.Reader)
Mox.defmock(MockTopic, for: Pipeline.Writer)
Mox.defmock(MockTable, for: Pipeline.Writer)
Mox.defmock(DateTimeMock, for: Forklift.Test.DateTimeBehaviour)
Mox.defmock(BrookMock, for: Forklift.Test.BrookBehaviour)
Mox.defmock(BrookEventMock, for: Forklift.Test.BrookEventBehaviour)
Mox.defmock(ElsaMock, for: Forklift.Test.ElsaBehaviour)
Mox.defmock(DataWriterMock, for: Forklift.Test.DataWriterBehaviour)
Mox.defmock(PrestigeHelperMock, for: Forklift.Test.PrestigeHelperBehaviour)
Mox.defmock(TelemetryEventMock, for: Forklift.Test.TelemetryEventBehaviour)
Mox.defmock(MockRedix, for: Forklift.Test.RedixBehaviour)
# Mox.defmock(MockMetricCollector, for: StreamingMetrics.MetricCollector)
