language: elixir
elixir:
  - '1.8.1'
otp_release:
  - '21.3'
services:
  - docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.1
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
install:
  - mix local.rebar --force;
  - mix local.hex --force
  - mix deps.get
  - mix format --check-formatted
  - mix credo
  - mix sobelow
script:
  - mix sobelow -i Config.HTTPS --skip --compact --exit low
  - docker build -t discovery_api:build .
  - mix test.integration
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh
    on:
      tags: true
branches:
  only:
  - master
  - /\d{1,3}\.\d{1,3}\.\d{1,3}/
