use Mix.Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
# config :andi, AndiWeb.Endpoint,
#   http: [:inet6, port: System.get_env("PORT") || 4000],
#   # url: [host: "example.com", port: 80],
#   # cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

config :andi, AndiWeb.Endpoint,
  pubsub: [name: AndiWeb.PubSub, adapter: Phoenix.PubSub.PG2],
  http: [port: {:system, "PORT"}],
  server: true,
  root: ".",
  cache_static_manifest: "priv/static/cache_manifest.json",
  version: Application.spec(:andi, :vsn),
  live_view: [
    signing_salt: "CHANGE BEFORE PROD"
  ]

config :andi,
  dead_letter_topic: "streaming-dead-letters"

host =
  case System.get_env("HOST_IP") do
    nil -> "localhost"
    defined -> defined
  end

endpoints = [{host, 9092}]

config :andi, :elsa,
  endpoints: endpoints,
  name: :andi_elsa,
  connection: :andi_reader,
  group_consumer: [
    name: "andi_reader",
    group: "andi_reader_group",
    topics: ["streaming-dead-letters"],
    handler: Andi.MessageHandler,
    handler_init_args: [],
    config: [
      begin_offset: 0,
      offset_reset_policy: :latest,
      prefetch_count: 0,
      prefetch_bytes: 2_097_152
    ]
  ]
