{{- if .Values.kafkaExporter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  labels:
    app.kubernetes.io/name: kafka-exporter
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-exporter
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: kafka-exporter
          ports:
            - containerPort: 9308
          image: "danielqsj/kafka-exporter:v1.4.1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9308
              scheme: HTTP
            initialDelaySeconds: 100
            timeoutSeconds: 9
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 1
          args: ["--kafka.server={{ .Values.kafka.broker }}"]
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 1Gi
              cpu: 500m
            requests:
              memory: 512Mi
              cpu: 300m
{{- end }}
