apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: discovery-ui
spec:
  selector:
    app: discovery-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: "{{ .Values.service.type }}"
