#!/bin/sh

_log() {
    level=${1}
    message=${2}

    if [ "error" = "${level}" ]; then
        echo 1>&2 "[${level}] ${message}"
    else
        echo "[${level}] ${message}"
    fi
}

host=${1:-streaming.smartcolumbusos.com}

_log info "Smoke test is starting"

payload='{"topic":"vehicle_position","event":"phx_join","payload":{},"ref":"1"}'

_log info "Sending payload \"${payload}\" to \"${host}\""
data=$(wscat -c wss://${host}/socket/websocket -x ${payload} -w 1)

lines=$(echo "${data}" | wc -l)

_log info "There were ${lines} lines of data in the response"

if test ${lines} -gt 1; then
    _log info "The smoke test succeeded"
else
    _log error "The smoke test failed (there weren't enough lines of response)"
    exit 1
fi
