name: All tests cron
on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  unit_tests:
    name: Run all unit tests
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        app: [andi, discovery_api]
    steps:
      - uses: actions/checkout@v2
        with:
          otp-version: 21.3.8
          elixir-version: 1.10.4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 21.3.8
          elixir-version: 1.10.4
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run unit tests
        run: |
          bash scripts/gh-action-unit-test.sh ${{ matrix.app }}
  integration_tests:
    name: Run all integration tests
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        app: [andi, discovery_api, pipeline, e2e]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 21.3.8
          elixir-version: 1.10.4
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run integration tests
        run: |
          bash scripts/gh-action-integration-test.sh ${{ matrix.app }}
