name: e2e
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  ci:
    if: github.event.pull_request.draft == false
    name: Verify Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 21.3.8.24
          version-type: strict
          elixir-version: 1.10.4
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run static checks
        run: |
          bash scripts/gh-action-static-checks.sh ${GITHUB_WORKFLOW}
      - name: Run integration tests
        run: |
          bash scripts/gh-action-integration-test.sh ${GITHUB_WORKFLOW}
      - if: always() && github.ref == 'refs/heads/master'
        name: Report Status
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
