name: estuary
on:
  push:
    branches:
      - master
    paths:
      - "apps/estuary/**"
      - "mix.lock"
  pull_request:
    branches:
      - master
    paths:
      - "apps/estuary/**"
      - "mix.lock"
  workflow_dispatch:
    branches:
      - master

jobs:
  ci:
    if: github.event.pull_request.draft == false
    name: Verify Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: 21.3
          elixir-version: 1.10.4
          experimental-otp: true
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run static checks
        run: |
          bash scripts/gh-action-static-checks.sh ${GITHUB_WORKFLOW}
      - name: Run unit tests
        run: |
          bash scripts/gh-action-unit-test.sh ${GITHUB_WORKFLOW}
      - name: Build docker image
        run: |
          bash scripts/build.sh ${GITHUB_WORKFLOW} development true
        if: github.event_name == 'pull_request'
      - name: Publish development image
        run: |
          bash scripts/gh-action-publish.sh ${GITHUB_WORKFLOW}
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
