name: providers
on:
  push:
    branches:
      - master
    paths:
      - "apps/providers/**"
      - "mix.lock"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
    paths:
      - "apps/providers/**"
      - "mix.lock"

jobs:
  ci:
    if: github.event.pull_request.draft == false
    name: Verify Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: 21.3
          elixir-version: 1.10.4
          experimental-otp: true
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run static checks
        run: |
          bash scripts/gh-action-static-checks.sh ${GITHUB_WORKFLOW}
      - name: Run unit tests
        run: |
          bash scripts/gh-action-unit-test.sh ${GITHUB_WORKFLOW}
