name: release
on:
  release:
    types: [created]

jobs:
  ci:
    name: Publish Docker Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.3 # 21.3.8.24
          version-type: strict
          elixir-version: 1.14 # 1.10.4
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Build
        run: |
          bash scripts/gh-action-release.sh ${GITHUB_REF}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      - if: always() && github.ref == 'refs/heads/master'
        name: Report Status
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
