name: test master cron
on:
  schedule:
    - cron: '0 5 * * *' 
jobs:
  dependencies:
    name: Get Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: 21.3
          elixir-version: 1.10.4
          experimental-otp: true
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
  test_matrix:
    name: Run all tests
    runs-on: ubuntu-latest
    needs: dependencies
    strategy:
      matrix:
        app: [andi, discovery_api, pipeline, e2e]
    steps:
      - name: Run static checks
        run: |
          bash scripts/gh-action-static-checks.sh ${{ matrix.app }}
      - name: Run unit tests
        run: |
          bash scripts/gh-action-unit-test.sh ${{ matrix.app }}
      - name: Run integration tests
        run: |
          bash scripts/gh-action-integration-test.sh ${{ matrix.app }}
