name: valkyrie
on:
  push:
    branches:
      - master
    paths:
      - "apps/valkyrie/**"
      - "mix.lock"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master
    paths:
      - "apps/valkyrie/**"
      - "mix.lock"
  workflow_dispatch:
    branches:
      - master

jobs:
  ci:
    if: github.event.pull_request.draft == false
    name: Verify Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1.5.0
        with:
          otp-version: 21.3
          elixir-version: 1.10.4
          experimental-otp: true
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Run static checks
        run: |
          bash scripts/gh-action-static-checks.sh ${GITHUB_WORKFLOW}
      - name: Run unit tests
        run: |
          bash scripts/gh-action-unit-test.sh ${GITHUB_WORKFLOW}
      - name: Run integration tests
        run: |
          bash scripts/gh-action-integration-test.sh ${GITHUB_WORKFLOW}
      - name: Publish development image
        run: |
          bash scripts/gh-action-publish.sh ${GITHUB_WORKFLOW}
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish to Quay
        run: |
          bash scripts/gh-action-quay.sh ${GITHUB_WORKFLOW} development
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      - if: github.ref == 'refs/heads/master'
        name: Report Status Master
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          mention_groups: "SAZ94GDB8,!channel"
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
      - if: github.ref != 'refs/heads/master'
        name: Report Status PR
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          message_format: '{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}> for branch {branch}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
