name: version_checker
on: [pull_request]

jobs:
  check-apps-for-update:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.5.0
        with:
          elixir-version: 1.9
          otp-version: 22.2
          experimental-otp: true
          runs-on: ubuntu-latest
      - name: Get dependencies
        run: |
          bash scripts/gh-action-get-deps.sh
      - name: Git Stuff
        id: git
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* 
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: Check App versions
        run: |
          export MESSAGE=$(bash scripts/gh-action-check-version.sh)
          if [ -z "${MESSAGE}" ]; then
            echo "No app changes detected"
            exit 0
          else
            echo -e "${MESSAGE}"
            exit 1
          fi
          # echo -e "${MESSAGE:-No app changes detected}" > comment-updates.txt
        id: differ
      # - name: Comment PR
      #   uses: marocchino/sticky-pull-request-comment@v1
      #   with:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     path: comment-updates.txt
